language: php
php:
  - '7.1'
before_install:
  - sudo apt-get install python-pygments

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit --verbose || travis_terminate 1
  - vendor/bin/php-cs-fixer --diff --dry-run --stop-on-violation --verbose fix

after_success:
- travis_retry php vendor/bin/coveralls