language: php
php:
  - '7.1'
  - '7.3'
before_install:
  - sudo apt-get install python-pygments

#cache:
#  directories:
#    - $HOME/.composer/cache

install:
  - gem install compass
  - composer install
  - curl -L http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar -o php-cs-fixer
  - sudo chmod a+x php-cs-fixer
  - sudo mv php-cs-fixer /usr/local/bin/php-cs-fixer

script:
  - vendor/bin/phpunit --verbose || travis_terminate 1
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php-cs-fixer --diff --dry-run --stop-on-violation --verbose fix -v; fi;'

after_script:
  - vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"

after_success:
#  - travis_retry php vendor/bin/coveralls
  # or enable logging
  - travis_retry php vendor/bin/coveralls -v
