language: php
php:
  - '7.1'
before_install:
  - sudo apt-get install python-pygments

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit --verbose || travis_terminate 1
  - vendor/bin/php-cs-fixer --diff --dry-run --stop-on-violation --verbose fix

after_script:
  - vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"